# -*- coding: utf-8 -*-
"""exercicioFor-While.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d-wamEmrQNZYelilPpCm2U_cCKZuo2vI
"""

# Solicitar um número inteirio positivo N ao usuário. Imprimir os números de N a 1. Realizar o exercício usando loops for e while.

N = int(input('Entre com número inteiro maior que 1: '))

# FOR
print('For:', end =' ')
for n in range(N):
  print(f'{N-n}', end=' -> ')
print('Fim\n')

# WHILE
print('While:', end =' ')
contador = 0
while contador < N:
  print(f'{N-contador}', end=' -> ')
  contador += 1
print('Fim')

# Solicitar um número inteiro positivo N ao usuário.
# Imprimir os números de N a 1 trocando o sinal dos números.
# Realizar o exercício usando loops for e while.

N = int(input('Digite um valor maior que 1: '))
mult = -1
fat = 1

#FOR
print('For:', end=' ')
for n in range(N):
  num = fat * (N-n)
  fat *= mult
  print(num, end=' ')
print('Fim\n')

#WHILE
print('While:', end=' ')
mult = -1
fat = 1
contador = 0
while contador < N:
  num = fat * (N-contador)
  fat *= mult
  print(num, end=' ')
  contador += 1
print('Fim')

N = int(input('Digite um número maior que 1: '))

#FOR
print('For: ')
for contador in range(1, N):
  print(contador * contador, end=' -> ')
print('Fim!\n')

#WHITE
print('While: ')
contador = 1
while contador < N:
  print(contador * contador, end=' -> ')
  contador += 1
print('Fim!\n')

# Solicitar uma palavra ao usuário e dizer se a palavra é um palíndromo, isto é, pode ser lida igualmente da esquerda para a direita e vice-versa.
# Exemplos de palavras que são palíndromos: ovo, radar, arara, reviver, Algumas dicas:

#Título
print('FOR'.center(50))
print('-'*50)
print('Identificador de Palíndromos'.center(50))
print('-'*50)

#Pergunta a palavra para o usuário
palavra = str(input('Digite uma palavra: ')).upper().strip()  #São colocadas todas em maiúsculas e excluido qualquer espaço em sua volta.
inverso = ''                                                  #Cria uma variável para ser preenchida após a estrutura de repetição.
for c in range(len(palavra)-1, -1, -1):                       #Para contador no range de quantidade de palavras - 1, com o -1 na segunda e terceira casa para que haja uma diminuição.
  inverso += palavra[c]                                       #Inverso recebe a palavra através da sua caractere.

print('='*50)                                                 #Divisor de linhas

#Estrutura Lógica
if palavra == inverso:
  print(f'As palavras são Palíndromos!\nDigitado: {palavra}.\nInverso: {inverso}.')
else:
  print(f'As palavras não são Palíndromos!\nDigitado: {palavra}.\nInverso: {inverso}.')

# Fazer um programa que solicita um número inteiro positivo N ao usuário e imprime um padrão na tela.

n = int(input('Digite um valor para impressão: '))

# FOR
print(' -' * n)
print('FOR'.center(n*2))
print(' -' * n)

print('', '-' * n, '')
for N in range(n):
  print('| ',end='')
  print(' ' * (n - 1), end='')
  print('|')
print('', '-' * n, '')

# WHILE
print(' -' * n)
print('WHILE'.center(n*2))
print(' -' * n)

contador = 0

print('', '-' * n, '')
while contador < n:
  print('| ',end='')
  print(' ' * (n - 1), end='')
  print('|')
  contador += 1
print('', '-' * n, '')

# Fazer um programa que solicita um número inteiro positivo N ao usuário e imprime um padrão na tela.

quantidade = int(input('Digite um valor para N: '))

print('-' * 30)
print('FOR'.center(30))
print('-' * 30)

for x in range(quantidade + 1):
  print('+' * x)

contador = 0

print('-' * 30)
print('WHILE'.center(30))
print('-' * 30)

while contador < quantidade + 1:
  print('+' * contador)
  contador += 1